### ISSUE TITLE
更新到最新版无法启动mtp了！

### ISSUE THREAD

**Issue by lukemin** [whunt1/onekeymakemtg#1]
mtg: error: unknown short flag '-b', try --help

**Comment by lukemin** [comment]
卸载的时候也有错误提示
The service command supports only basic LSB actions (start, stop, restart, try-restart, reload, force-reload, status). For other actions, please try to use systemctl.

**Comment by whunt1** [comment]
今天更新了，支持TLS伪装，因为变动比较多，管理脚本也改了，先卸载旧的 mtp ，删除脚本，然后重新下载安装最新脚本

不能卸载的话直接执行 `rm -rf /usr/local/mtproxy-go`

**Comment by lukemin** [comment]
谢谢，更新

**Comment by lukemin** [comment]
centos7 用的Firewalld控制，而不是iptables，能不能再更新一下？？

**Comment by whunt1** [comment]
你可以考虑卸载 firewalld，安装 iptables，或者手动放行端口，因为我感觉 firewalld 真的不好用

**Comment by zishiguo** [comment]
请问，有人解决了嘛？
