### ISSUE TITLE
加了TAG就无法连接

### ISSUE THREAD

**Issue by wenpo1975** [whunt1/onekeymakemtg#13]
加了AD TAG就无法连接
去掉AD TAG就连接正常，TAG是https://t.me/MTProxybot 生成的
回复的8424000edf0ca2e2cb6fc6e786f9d4XX应该也没错
但是设置上TAG 就是无法连接，一直在刷新中

**Comment by barbiekingkong** [comment]
您好，您的邮件我已经收到了，我会在第一时间给您回复的，谢谢~  鲍澎
