### ISSUE TITLE
安装失败 !

### ISSUE THREAD

**Issue by geekbb** [whunt1/onekeymakemtg#7]
/dl/go1.14.4.linux-amd64.tar.gz: 地址缺少协议类型.
tar: go*linux-amd64.tar.gz：无法 open: 没有那个文件或目录
tar: Error is not recoverable: exiting now
mv: 无法获取"go" 的文件状态(stat): 没有那个文件或目录
[错误] go 安装失败 !

**Comment by obeykarma** [comment]
是的，我也碰到同样问题！

**Comment by LeiD215** [comment]
我也碰到了一样的问题。

**Comment by muihiuwev** [comment]
CentOS 7 同，怕喝茶，所以改成不能用了？

**Comment by LeiD215** [comment]
另外开机自启功能无效。

**Comment by muihiuwev** [comment]
手动编译，可用，开机启动可赋权并编辑 `/etc/rc.d/rc.local` 添加运行命令 `nohup mtg run -b 0.0.0.0:8443 --cloak-port=8443 ee9cd99f007fcd0511eac85eb87e12*** >> /tmp/mtg.log 2>&1 &`

**Comment by LeiD215** [comment]
脚本在/etc/init.d/目录下新建了mtproxy-go，使用chkconfig将脚本加入服务，自启功能无效。

**Comment by geekbb** [comment]
> 手动编译，可用，启动启动可赋权并编辑`/etc/rc.d/rc.local`添加运行命令`nohup mtg run -b 0.0.0.0:8443 --cloak-port=8443 ee9cd99f007fcd0511eac85eb87e12*** >> /tmp/mtg.log 2>&1 &`

我要是会手动编译，还找一键脚本做什么，哈哈哈哈

**Comment by LeiD215** [comment]
> > 手动编译，可用，启动启动可赋权并编辑`/etc/rc.d/rc.local`添加运行命令`nohup mtg run -b 0.0.0.0:8443 --cloak-port=8443 ee9cd99f007fcd0511eac85eb87e12*** >> /tmp/mtg.log 2>&1 &`
> 
> 我还是会手动编译，还找一键脚本做什么，哈哈哈哈

呃 其实手动编译的话 修改下脚本 把下载GO的连接直接改成直连，脚本运行就正常了。

**Comment by janeyee110** [comment]
> > 手动编译，可用，启动启动可赋权并编辑`/etc/rc.d/rc.local`添加运行命令`nohup mtg run -b 0.0.0.0:8443 --cloak-port=8443 ee9cd99f007fcd0511eac85eb87e12*** >> /tmp/mtg.log 2>&1 &`
> 
> 我要是会手动编译，还找一键脚本做什么，哈哈哈哈

那尝试一下其他一键脚本吧
https://github.com/ellermister/mtproxy
https://github.com/cutelua/mtg-dist

**Comment by zjsailor** [comment]
> /dl/go1.14.4.linux-amd64.tar.gz: 地址缺少协议类型.
> tar: go*linux-amd64.tar.gz：无法 open: 没有那个文件或目录
> tar: Error is not recoverable: exiting now
> mv: 无法获取"go" 的文件状态(stat): 没有那个文件或目录
> [错误] go 安装失败 !

只是无法下载文件而已
编辑  mtproxy-go.sh文件
把118行的下载地址换成下面这个即可。
wget -N --no-check-certificate https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz

**Comment by lukemin** [comment]
> > /dl/go1.14.4.linux-amd64.tar.gz: 地址缺少协议类型.
> > tar: go*linux-amd64.tar.gz：无法 open: 没有那个文件或目录
> > tar: Error is not recoverable: exiting now
> > mv: 无法获取"go" 的文件状态(stat): 没有那个文件或目录
> > [错误] go 安装失败 !
> 
> 只是无法下载文件而已
> 编辑 mtproxy-go.sh文件
> 把118行的下载地址换成下面这个即可。
> wget -N --no-check-certificate https://dl.google.com/go/go1.13.4.linux-amd64.tar.gz

这样吧golang的版本写死了，如果想用最新的版本，把118行修改为：
wget -N --no-check-certificate https://golang.org${go_download_link}

**Comment by kkunn0** [comment]
找到go_download_link=，手动改成go_download_link="https://golang.org/dl/go1.15.5.linux-amd64.tar.gz"
